- name: install xvfb
  become: yes
  apt: pkg=xvfb

- name: add Google Linux repo signing key
  become: yes
  apt_key: id=7FAC5991
           url=https://dl-ssl.google.com/linux/linux_signing_key.pub
           state=present

- name: add Google Chrome repository
  become: yes
  apt_repository: repo='deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' state=present

- name: install Google Chrome
  become: yes
  apt: pkg=google-chrome-stable

- name: install unzip
  become: yes
  apt: name=unzip state=present

- name: download chromedriver
  become: yes
  unarchive: src=https://chromedriver.storage.googleapis.com/{{ chromedriver_version }}/chromedriver_linux{{ ansible_userspace_bits }}.zip dest=/tmp copy=no

- name: copy executable file for chromedriver
  become: yes
  copy: src=/tmp/chromedriver dest=/usr/local/bin/chromedriver mode=0755 remote_src=yes

- name: expore display to allow selenium to work
  lineinfile:
    dest: "{{ user_home}}.profile"
    line: "export DISPLAY=:99"

# This is probably the wrong place for this,
# it should be tied to systemd startup rather
# than a profile thing *I think*.
- name: start Xvfb on login
  lineinfile:
    dest: "{{ user_home}}.profile"
    line: "Xvfb -ac :99 2>/dev/null &"
